
cellInfo = { ...
{...
'HVAC_Ctrl_Bus',...
'',...
sprintf('HVAC control signal'), ...
'Auto',...
'-1', {...
{'HVAC_Ctrl_AC_cmpr', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HVAC control AC compressor drive' };...
 } ...
 } ...
{...
'HVAC_Ctrl_VehCAN_Rx_Bus',...
'',...
sprintf('HVAC control vehicle CAN receive signal bus'), ...
'Auto',...
'-1', {...
{'EngCtrl_Engine_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rpm', 'Engine control engine speed' };...
{'HEVCtrl_IdleStop_preparation_request', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HEV control idle stop preparation request' };...
{'HEVCtrl_IdleStop_status', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HEV control idle stop status' };...
 } ...
 } ...
{...
'HVAC_Ctrl_VehCAN_Tx_Bus',...
'',...
sprintf('HVAC control vehicle CAN transmit signal bus'), ...
'Auto',...
'-1', {...
{'HVAC_Ctrl_Idlestop_enbl', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HVAC control Idle stop enable' };...
{'HVAC_Ctrl_Idlestop_cancel', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HVAC control Idle stop cancel ' };...
 } ...
 } ...
 }';
 Simulink.Bus.cellToObject(cellInfo);
 clear cellInfo 
