% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Nov-2018 11:16:01
%  MATLAB version: 9.4.0.949201 (R2018a) Update 6
% -------------------------------------------------------------------
saveVarsMat = load('Config_Plant_MILS_VarStep.mat');

Config_Plant = saveVarsMat.Config_Plant; % <1x1 Simulink.ConfigSet>  T | [ g         J X ^    R   | [ l   g

clear saveVarsMat;
