% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Nov-2018 13:39:48
%  MATLAB version: 9.4.0.949201 (R2018a) Update 6
% -------------------------------------------------------------------
                                                  

Config_Ctrl_Module = Simulink.ConfigSet;
Config_Ctrl_Module.set_param('Name', 'Config_Ctrl_Module_MILS');
Config_Ctrl_Module.set_param('Description', ['制御モデルのモジュール（A' ...
                              'utosar Runnable）用Configurationパラメー' ...
                              'タ', char(10), 'MILS用　固定ステップ　離' ...
                              '散のみ　サンプリング時間に依存しない']);
Config_Ctrl_Module.set_param('SystemTargetFile', 'grt.tlc');
Config_Ctrl_Module.set_param('HardwareBoard', 'None');
Config_Ctrl_Module.set_param('Solver', 'FixedStepDiscrete');
Config_Ctrl_Module.set_param('StartTime', '0.0');
Config_Ctrl_Module.set_param('StopTime', '10.0');
Config_Ctrl_Module.set_param('SampleTimeConstraint', 'STIndependent');
Config_Ctrl_Module.set_param('SolverType', 'Fixed-step');
Config_Ctrl_Module.set_param('LoadExternalInput', 'off');
Config_Ctrl_Module.set_param('LoadInitialState', 'off');
Config_Ctrl_Module.set_param('SaveTime', 'on');
Config_Ctrl_Module.set_param('TimeSaveName', 'tout');
Config_Ctrl_Module.set_param('SaveState', 'off');
Config_Ctrl_Module.set_param('SaveFormat', 'Array');
Config_Ctrl_Module.set_param('SaveOutput', 'off');
Config_Ctrl_Module.set_param('SaveFinalState', 'off');
Config_Ctrl_Module.set_param('SignalLogging', 'on');
Config_Ctrl_Module.set_param('SignalLoggingName', 'logsout');
Config_Ctrl_Module.set_param('DSMLogging', 'on');
Config_Ctrl_Module.set_param('DSMLoggingName', 'dsmout');
Config_Ctrl_Module.set_param('LoggingToFile', 'off');
Config_Ctrl_Module.set_param('DatasetSignalFormat', 'timeseries');
Config_Ctrl_Module.set_param('ReturnWorkspaceOutputs', 'off');
Config_Ctrl_Module.set_param('InspectSignalLogs', 'off');
Config_Ctrl_Module.set_param('LimitDataPoints', 'on');
Config_Ctrl_Module.set_param('MaxDataPoints', '1000');
Config_Ctrl_Module.set_param('Decimation', '1');
Config_Ctrl_Module.set_param('BlockReduction', 'on');
Config_Ctrl_Module.set_param('OptimizeBlockIOStorage', 'on');
Config_Ctrl_Module.set_param('DataBitsets', 'off');
Config_Ctrl_Module.set_param('StateBitsets', 'off');
Config_Ctrl_Module.set_param('EnableMemcpy', 'on');
Config_Ctrl_Module.set_param('BufferReuse', 'on');
Config_Ctrl_Module.set_param('ExpressionFolding', 'on');
Config_Ctrl_Module.set_param('LocalBlockOutputs', 'on');
Config_Ctrl_Module.set_param('ConditionallyExecuteInputs', 'on');
Config_Ctrl_Module.set_param('BooleanDataType', 'on');
Config_Ctrl_Module.set_param('LifeSpan', 'inf');
Config_Ctrl_Module.set_param('UseDivisionForNetSlopeComputation', 'off');
Config_Ctrl_Module.set_param('UseFloatMulNetSlope', 'off');
Config_Ctrl_Module.set_param('DefaultUnderspecifiedDataType', 'double');
Config_Ctrl_Module.set_param('InitFltsAndDblsToZero', 'off');
Config_Ctrl_Module.set_param('EfficientFloat2IntCast', 'off');
Config_Ctrl_Module.set_param('EfficientMapNaN2IntZero', 'on');
Config_Ctrl_Module.set_param('SimCompilerOptimization', 'off');
Config_Ctrl_Module.set_param('AccelVerboseBuild', 'off');
Config_Ctrl_Module.set_param('DefaultParameterBehavior', 'Inlined');
Config_Ctrl_Module.set_param('MemcpyThreshold', 64);
Config_Ctrl_Module.set_param('InlineInvariantSignals', 'off');
Config_Ctrl_Module.set_param('RollThreshold', 5);
Config_Ctrl_Module.set_param('MaxStackSize', 'Inherit from target');
Config_Ctrl_Module.set_param('ActiveStateOutputEnumStorageType', ['Nati' ...
                              've Integer']);
Config_Ctrl_Module.set_param('BufferReusableBoundary', 'on');
Config_Ctrl_Module.set_param('AlgebraicLoopMsg', 'warning');
Config_Ctrl_Module.set_param('ArtificialAlgebraicLoopMsg', 'warning');
Config_Ctrl_Module.set_param('BlockPriorityViolationMsg', 'warning');
Config_Ctrl_Module.set_param('MinStepSizeMsg', 'warning');
Config_Ctrl_Module.set_param('TimeAdjustmentMsg', 'none');
Config_Ctrl_Module.set_param('MaxConsecutiveZCsMsg', 'error');
Config_Ctrl_Module.set_param('UnknownTsInhSupMsg', 'warning');
Config_Ctrl_Module.set_param('ConsistencyChecking', 'none');
Config_Ctrl_Module.set_param('SolverPrmCheckMsg', 'warning');
Config_Ctrl_Module.set_param('ModelReferenceExtraNoncontSigs', 'error');
Config_Ctrl_Module.set_param('StateNameClashWarn', 'warning');
Config_Ctrl_Module.set_param('SimStateInterfaceChecksumMismatchMsg', ['w' ...
                              'arning']);
Config_Ctrl_Module.set_param('SimStateOlderReleaseMsg', 'error');
Config_Ctrl_Module.set_param('InheritedTsInSrcMsg', 'warning');
Config_Ctrl_Module.set_param('MultiTaskRateTransMsg', 'error');
Config_Ctrl_Module.set_param('SingleTaskRateTransMsg', 'none');
Config_Ctrl_Module.set_param('MultiTaskCondExecSysMsg', 'error');
Config_Ctrl_Module.set_param('TasksWithSamePriorityMsg', 'warning');
Config_Ctrl_Module.set_param('SigSpecEnsureSampleTimeMsg', 'warning');
Config_Ctrl_Module.set_param('SignalResolutionControl', ['UseLocalSetti' ...
                              'ngs']);
Config_Ctrl_Module.set_param('CheckMatrixSingularityMsg', 'none');
Config_Ctrl_Module.set_param('IntegerSaturationMsg', 'warning');
Config_Ctrl_Module.set_param('UnderSpecifiedDataTypeMsg', 'none');
Config_Ctrl_Module.set_param('SignalRangeChecking', 'none');
Config_Ctrl_Module.set_param('IntegerOverflowMsg', 'warning');
Config_Ctrl_Module.set_param('SignalInfNanChecking', 'none');
Config_Ctrl_Module.set_param('StringTruncationChecking', 'error');
Config_Ctrl_Module.set_param('RTPrefix', 'error');
Config_Ctrl_Module.set_param('ParameterDowncastMsg', 'error');
Config_Ctrl_Module.set_param('ParameterOverflowMsg', 'error');
Config_Ctrl_Module.set_param('ParameterUnderflowMsg', 'none');
Config_Ctrl_Module.set_param('ParameterPrecisionLossMsg', 'warning');
Config_Ctrl_Module.set_param('ParameterTunabilityLossMsg', 'warning');
Config_Ctrl_Module.set_param('ReadBeforeWriteMsg', 'UseLocalSettings');
Config_Ctrl_Module.set_param('WriteAfterReadMsg', 'UseLocalSettings');
Config_Ctrl_Module.set_param('WriteAfterWriteMsg', 'UseLocalSettings');
Config_Ctrl_Module.set_param('MultiTaskDSMMsg', 'error');
Config_Ctrl_Module.set_param('UniqueDataStoreMsg', 'none');
Config_Ctrl_Module.set_param('UnderspecifiedInitializationDetection', ['C' ...
                              'lassic']);
Config_Ctrl_Module.set_param('MergeDetectMultiDrivingBlocksExec', ['non' ...
                              'e']);
Config_Ctrl_Module.set_param('CheckSSInitialOutputMsg', 'on');
Config_Ctrl_Module.set_param('CheckExecutionContextRuntimeOutputMsg', ['o' ...
                              'ff']);
Config_Ctrl_Module.set_param('ArrayBoundsChecking', 'none');
Config_Ctrl_Module.set_param('AssertControl', 'UseLocalSettings');
Config_Ctrl_Module.set_param('AllowSymbolicDim', 'on');
Config_Ctrl_Module.set_param('UnnecessaryDatatypeConvMsg', 'none');
Config_Ctrl_Module.set_param('VectorMatrixConversionMsg', 'none');
Config_Ctrl_Module.set_param('Int32ToFloatConvMsg', 'warning');
Config_Ctrl_Module.set_param('FixptConstUnderflowMsg', 'none');
Config_Ctrl_Module.set_param('FixptConstOverflowMsg', 'none');
Config_Ctrl_Module.set_param('FixptConstPrecisionLossMsg', 'none');
Config_Ctrl_Module.set_param('SignalLabelMismatchMsg', 'none');
Config_Ctrl_Module.set_param('UnconnectedInputMsg', 'warning');
Config_Ctrl_Module.set_param('UnconnectedOutputMsg', 'warning');
Config_Ctrl_Module.set_param('UnconnectedLineMsg', 'warning');
Config_Ctrl_Module.set_param('RootOutportRequireBusObject', 'warning');
Config_Ctrl_Module.set_param('BusObjectLabelMismatch', 'warning');
Config_Ctrl_Module.set_param('StrictBusMsg', 'ErrorLevel1');
Config_Ctrl_Module.set_param('NonBusSignalsTreatedAsBus', 'none');
Config_Ctrl_Module.set_param('BusNameAdapt', 'WarnAndRepair');
Config_Ctrl_Module.set_param('InvalidFcnCallConnMsg', 'error');
Config_Ctrl_Module.set_param('FcnCallInpInsideContextMsg', 'warning');
Config_Ctrl_Module.set_param('SFcnCompatibilityMsg', 'none');
Config_Ctrl_Module.set_param('FrameProcessingCompatibilityMsg', 'error');
Config_Ctrl_Module.set_param('ModelReferenceVersionMismatchMessage', ['n' ...
                              'one']);
Config_Ctrl_Module.set_param('ModelReferenceIOMismatchMessage', 'none');
Config_Ctrl_Module.set_param('ModelReferenceIOMsg', 'none');
Config_Ctrl_Module.set_param('ModelReferenceDataLoggingMessage', ['warn' ...
                              'ing']);
Config_Ctrl_Module.set_param('SaveWithDisabledLinksMsg', 'warning');
Config_Ctrl_Module.set_param('SaveWithParameterizedLinksMsg', 'warning');
Config_Ctrl_Module.set_param('SFUnusedDataAndEventsDiag', 'warning');
Config_Ctrl_Module.set_param('SFUnexpectedBacktrackingDiag', 'warning');
Config_Ctrl_Module.set_param('SFInvalidInputDataAccessInChartInitDiag', ...
                              'warning');
Config_Ctrl_Module.set_param('SFNoUnconditionalDefaultTransitionDiag', ...
                              'warning');
Config_Ctrl_Module.set_param('SFTransitionOutsideNaturalParentDiag', ['w' ...
                              'arning']);
Config_Ctrl_Module.set_param('SFUnreachableExecutionPathDiag', ['warnin' ...
                              'g']);
Config_Ctrl_Module.set_param('SFUndirectedBroadcastEventsDiag', ['warni' ...
                              'ng']);
Config_Ctrl_Module.set_param('SFTransitionActionBeforeConditionDiag', ['w' ...
                              'arning']);
Config_Ctrl_Module.set_param('SFOutputUsedAsStateInMooreChartDiag', ['e' ...
                              'rror']);
Config_Ctrl_Module.set_param('SFTemporalDelaySmallerThanSampleTimeDiag', ...
                              'warning');
Config_Ctrl_Module.set_param('SFSelfTransitionDiag', 'warning');
Config_Ctrl_Module.set_param('SFExecutionAtInitializationDiag', 'none');
Config_Ctrl_Module.set_param('SFMachineParentedDataDiag', 'warning');
Config_Ctrl_Module.set_param('IgnoredZcDiagnostic', 'warning');
Config_Ctrl_Module.set_param('InitInArrayFormatMsg', 'warning');
Config_Ctrl_Module.set_param('MaskedZcDiagnostic', 'warning');
Config_Ctrl_Module.set_param('ModelReferenceSymbolNameMessage', ['warni' ...
                              'ng']);
Config_Ctrl_Module.set_param('AllowedUnitSystems', 'all');
Config_Ctrl_Module.set_param('UnitsInconsistencyMsg', 'warning');
Config_Ctrl_Module.set_param('AllowAutomaticUnitConversions', 'on');
Config_Ctrl_Module.set_param('ForceCombineOutputUpdateInSim', 'off');
Config_Ctrl_Module.set_param('ProdHWDeviceType', '32-bit Generic');
Config_Ctrl_Module.set_param('ProdLargestAtomicInteger', 'Char');
Config_Ctrl_Module.set_param('ProdLargestAtomicFloat', 'None');
Config_Ctrl_Module.set_param('ProdIntDivRoundTo', 'Undefined');
Config_Ctrl_Module.set_param('ProdEqTarget', 'on');
Config_Ctrl_Module.set_param('TargetPreprocMaxBitsSint', 32);
Config_Ctrl_Module.set_param('TargetPreprocMaxBitsUint', 32);
Config_Ctrl_Module.set_param('UpdateModelReferenceTargets', ['IfOutOfDa' ...
                              'te']);
Config_Ctrl_Module.set_param('EnableParallelModelReferenceBuilds', ['of' ...
                              'f']);
Config_Ctrl_Module.set_param('ModelReferenceNumInstancesAllowed', ['Mul' ...
                              'ti']);
Config_Ctrl_Module.set_param('PropagateVarSize', ['Infer from blocks in' ...
                              ' model']);
Config_Ctrl_Module.set_param('ModelReferenceMinAlgLoopOccurrences', ['o' ...
                              'ff']);
Config_Ctrl_Module.set_param('EnableRefExpFcnMdlSchedulingChecks', 'on');
Config_Ctrl_Module.set_param('PropagateSignalLabelsOutOfModel', 'off');
Config_Ctrl_Module.set_param('ModelReferencePassRootInputsByReference', ...
                              'on');
Config_Ctrl_Module.set_param('ModelDependencies', '');
Config_Ctrl_Module.set_param('ParallelModelReferenceErrorOnInvalidPool', ...
                              'on');
Config_Ctrl_Module.set_param('SupportModelReferenceSimTargetCustomCode', ...
                              'off');
Config_Ctrl_Module.set_param('MATLABDynamicMemAlloc', 'on');
Config_Ctrl_Module.set_param('MATLABDynamicMemAllocThreshold', 65536);
Config_Ctrl_Module.set_param('CompileTimeRecursionLimit', 50);
Config_Ctrl_Module.set_param('EnableRuntimeRecursion', 'on');
Config_Ctrl_Module.set_param('SFSimEcho', 'on');
Config_Ctrl_Module.set_param('SimCtrlC', 'on');
Config_Ctrl_Module.set_param('SimIntegrity', 'on');
Config_Ctrl_Module.set_param('SimGenImportedTypeDefs', 'off');
Config_Ctrl_Module.set_param('SimBuildMode', 'sf_incremental_build');
Config_Ctrl_Module.set_param('SimReservedNameArray', []);
Config_Ctrl_Module.set_param('SimParseCustomCode', 'on');
Config_Ctrl_Module.set_param('SimCustomSourceCode', '');
Config_Ctrl_Module.set_param('SimCustomHeaderCode', '');
Config_Ctrl_Module.set_param('SimCustomInitializer', '');
Config_Ctrl_Module.set_param('SimCustomTerminator', '');
Config_Ctrl_Module.set_param('SimUserIncludeDirs', '');
Config_Ctrl_Module.set_param('SimUserSources', '');
Config_Ctrl_Module.set_param('SimUserLibraries', '');
Config_Ctrl_Module.set_param('SimUserDefines', '');
Config_Ctrl_Module.set_param('SFSimEnableDebug', 'off');
Config_Ctrl_Module.set_param('TargetLang', 'C');
Config_Ctrl_Module.set_param('Toolchain', ['Automatically locate an ins' ...
                              'talled toolchain']);
Config_Ctrl_Module.set_param('BuildConfiguration', 'Faster Builds');
Config_Ctrl_Module.set_param('ObjectivePriorities', []);
Config_Ctrl_Module.set_param('CheckMdlBeforeBuild', 'Off');
Config_Ctrl_Module.set_param('GenCodeOnly', 'off');
Config_Ctrl_Module.set_param('PackageGeneratedCodeAndArtifacts', 'off');
Config_Ctrl_Module.set_param('RTWVerbose', 'on');
Config_Ctrl_Module.set_param('RetainRTWFile', 'off');
Config_Ctrl_Module.set_param('ProfileTLC', 'off');
Config_Ctrl_Module.set_param('TLCDebug', 'off');
Config_Ctrl_Module.set_param('TLCCoverage', 'off');
Config_Ctrl_Module.set_param('TLCAssert', 'off');
Config_Ctrl_Module.set_param('RTWUseSimCustomCode', 'off');
Config_Ctrl_Module.set_param('CustomSourceCode', '');
Config_Ctrl_Module.set_param('CustomHeaderCode', '');
Config_Ctrl_Module.set_param('CustomInclude', '');
Config_Ctrl_Module.set_param('CustomSource', '');
Config_Ctrl_Module.set_param('CustomLibrary', '');
Config_Ctrl_Module.set_param('CustomLAPACKCallback', '');
Config_Ctrl_Module.set_param('CustomFFTCallback', '');
Config_Ctrl_Module.set_param('CustomDefine', '');
Config_Ctrl_Module.set_param('CustomInitializer', '');
Config_Ctrl_Module.set_param('CustomTerminator', '');
Config_Ctrl_Module.set_param('PostCodeGenCommand', '');
Config_Ctrl_Module.set_param('SaveLog', 'off');
Config_Ctrl_Module.set_param('TLCOptions', '');
Config_Ctrl_Module.set_param('GenerateReport', 'off');
Config_Ctrl_Module.set_param('GenerateComments', 'on');
Config_Ctrl_Module.set_param('SimulinkBlockComments', 'on');
Config_Ctrl_Module.set_param('StateflowObjectComments', 'on');
Config_Ctrl_Module.set_param('MATLABSourceComments', 'off');
Config_Ctrl_Module.set_param('ShowEliminatedStatement', 'off');
Config_Ctrl_Module.set_param('ForceParamTrailComments', 'off');
Config_Ctrl_Module.set_param('MaxIdLength', 31);
Config_Ctrl_Module.set_param('UseSimReservedNames', 'off');
Config_Ctrl_Module.set_param('ReservedNameArray', []);
Config_Ctrl_Module.set_param('TargetLangStandard', 'C89/C90 (ANSI)');
Config_Ctrl_Module.set_param('CodeReplacementLibrary', 'None');
Config_Ctrl_Module.set_param('UtilityFuncGeneration', 'Auto');
Config_Ctrl_Module.set_param('CodeInterfacePackaging', ['Nonreusable fu' ...
                              'nction']);
Config_Ctrl_Module.set_param('GRTInterface', 'on');
Config_Ctrl_Module.set_param('SupportNonFinite', 'on');
Config_Ctrl_Module.set_param('MultiwordLength', 2048);
Config_Ctrl_Module.set_param('MatFileLogging', 'on');
Config_Ctrl_Module.set_param('LogVarNameModifier', 'rt_');
Config_Ctrl_Module.set_param('GenerateFullHeader', 'on');
Config_Ctrl_Module.set_param('InferredTypesCompatibility', 'off');
Config_Ctrl_Module.set_param('TargetLibSuffix', '');
Config_Ctrl_Module.set_param('TargetPreCompLibLocation', '');
Config_Ctrl_Module.set_param('LUTObjectStructOrderExplicitValues', ['Si' ...
                              'ze,Breakpoints,Table']);
Config_Ctrl_Module.set_param('LUTObjectStructOrderEvenSpacing', ['Size,' ...
                              'Breakpoints,Table']);
Config_Ctrl_Module.set_param('DynamicStringBufferSize', 256);
Config_Ctrl_Module.set_param('ExtMode', 'off');
Config_Ctrl_Module.set_param('RTWCAPIParams', 'off');
Config_Ctrl_Module.set_param('RTWCAPIRootIO', 'off');
Config_Ctrl_Module.set_param('RTWCAPISignals', 'off');
Config_Ctrl_Module.set_param('RTWCAPIStates', 'off');
Config_Ctrl_Module.set_param('GenerateASAP2', 'off');
Config_Ctrl_Module.set_param('CovModelRefEnable', 'off');
Config_Ctrl_Module.set_param('RecordCoverage', 'off');
Config_Ctrl_Module.set_param('CovEnable', 'off');

