
cellInfo = { ...
{...
'NAVI_InfoCAN_Rx_Bus',...
'',...
sprintf('Navigation information CAN receive'), ...
'Auto',...
'-1', {...
{'BrkCtrl_Vehicle_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'km/h', 'Brake control vehicle speed' };...
 } ...
 } ...
{...
'NAVI_InfoCAN_Tx_Bus',...
'',...
sprintf('Navigation information CAN transmit'), ...
'Auto',...
'-1', {...
{'NAVI_Road_information', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Navigation road informations ' };...
{'NAVI_Home_around_status', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Navigation home around status' };...
 } ...
 } ...
 }';
 Simulink.Bus.cellToObject(cellInfo);
 clear cellInfo 
