
cellInfo = { ...
{...
'BrakeCtrl_Bus',...
'',...
sprintf('Brake control signal bus'), ...
'Auto',...
'-1', {...
{'BrkCtrl_BrakeDem', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '%', 'Brake actuator demmand' };...
 } ...
 } ...
{...
'BrakeCtrl_VehCAN_Rx_Bus',...
'',...
sprintf('Brake control vehicle CAN receive signal bus'), ...
'Auto',...
'-1', {...
{'HEVCtrl_Regen_brake_torque_available', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', 'regeneratin brake available torque (wheel)' };...
{'HEVCtrl_Regen_brake_torque_actual', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', 'regeneratin brake actual torque (wheel)' };...
{'VMCtrl_BrakeForceStatus', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'VM control vehicle brake force status' };...
{'VMCtrl_BrakeForceCmnd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N', 'VM control vehicle brake force command' };...
 } ...
 } ...
{...
'BrakeCtrl_VehCAN_Tx_Bus',...
'',...
sprintf('Brake control vehicle CAN transmit signal bus'), ...
'Auto',...
'-1', {...
{'BrkCtrl_Vehicle_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'km/h', 'Brake control vehicle speed' };...
{'BrkCtrl_Regen_brake_torque_request', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', 'Brake control regeneration request torque' };...
 } ...
 } ...
{...
'BrakeCtrl_Info_Bus',...
'',...
sprintf('Brake control information signal bus'), ...
'Auto',...
'-1', {...
{'BrkCtrl_ReqBrkTrq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', 'Brake control required brake torque' };...
 } ...
 } ...
 }';
 Simulink.Bus.cellToObject(cellInfo);
 clear cellInfo 
