
cellInfo = { ...
{...
'SteerCtrl_Bus',...
'',...
sprintf('Steering control signal bus'), ...
'Auto',...
'-1', {...
{'StrgCtrl_Steer_assist_torque', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Steer assist torque' };...
 } ...
 } ...
{...
'SteerCtrl_VehCAN_Rx_Bus',...
'',...
sprintf('Steering control vehicle CAN receive signal bus'), ...
'Auto',...
'-1', {...
{'BrkCtrl_Vehicle_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'km/h', 'Brake control vehicle speed' };...
 } ...
 } ...
{...
'SteerCtrl_VehCAN_Tx_Bus',...
'',...
sprintf('Steering control vehicle CAN transmit signal bus'), ...
'Auto',...
'-1', {...
{'StrgCtrl_Steer_angle', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Steering control steer angle' };...
 } ...
 } ...
{...
'SteerCtrl_Info_Bus',...
'',...
sprintf('Steering control information signal bus'), ...
'Auto',...
'-1', {...
{'StrgCtrl_Steer_angle', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Steering control steer angle' };...
 } ...
 } ...
 }';
 Simulink.Bus.cellToObject(cellInfo);
 clear cellInfo 
