
cellInfo = { ...
{...
'CAN_Bus',...
'',...
sprintf(''), ...
'Auto',...
'-1', {...
{'InfoCAN', 1, 'Bus: InfoCAN_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Information CAN' };...
{'VehCAN', 1, 'Bus: VehCAN_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Vehicle CAN' };...
{'PwtrCAN', 1, 'Bus: PwtrCAN_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Powertrain CAN' };...
 } ...
 } ...
{...
'InfoCAN_Bus',...
'',...
sprintf('Information  CAN'), ...
'Auto',...
'-1', {...
{'NAVI_InfoCAN_Tx', 1, 'Bus: NAVI_InfoCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Navigation information CAN transmit' };...
{'Radar_InfoCAN_Tx', 1, 'Bus: Radar_InfoCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Radar information CAN transmit' };...
 } ...
 } ...
{...
'VehCAN_Bus',...
'',...
sprintf('Vehicle CAN'), ...
'Auto',...
'-1', {...
{'VM_Ctrl_VehCAN_Tx', 1, 'Bus: VM_Ctrl_VehCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Vehicle Motion Control vehicle CAN transmit signal bus' };...
{'BrakeCtrl_VehCAN_Tx', 1, 'Bus: BrakeCtrl_VehCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Brake control vehicle CAN transmit signal bus' };...
{'SteerCtrl_VehCAN_Tx', 1, 'Bus: SteerCtrl_VehCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Steering control vehicle CAN transmit signal bus' };...
{'HVAC_Ctrl_VehCAN_Tx', 1, 'Bus: HVAC_Ctrl_VehCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HVAC control vehicle CAN transmit signal bus' };...
{'BodyCtrl_VehCAN_Tx', 1, 'Bus: BodyCtrl_VehCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Body control vehicle CAN transmit signal bus ' };...
 } ...
 } ...
{...
'PwtrCAN_Bus',...
'',...
sprintf('Powertrain CAN'), ...
'Auto',...
'-1', {...
{'HEV_Ctrl_PwtrCAN_Tx', 1, 'Bus: HEV_Ctrl_PwtrCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HEV control powertrain CAN transmit signal bus' };...
{'EngineCtrl_PwtrCAN_Tx', 1, 'Bus: EngineCtrl_PwtrCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Engine control powertrain CAN transmit signal bus' };...
{'TransmCtrl_PwtrCAN_Tx', 1, 'Bus: TransmCtrl_PwtrCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Transmission control CAN transmit signal bus' };...
{'MotorCtrl_PwtrCAN_Tx', 1, 'Bus: MotorCtrl_PwtrCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Motor control powertrain CAN  transmit signal bus' };...
{'BatteryCtrl_PwtrCAN_Tx', 1, 'Bus: BatteryCtrl_PwtrCAN_Tx_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Battery control powertrain CAN transmit signal bus' };...
 } ...
 } ...
{...
'IntgCtrl_Info_Bus',...
'',...
sprintf('controlles information signals'), ...
'Auto',...
'-1', {...
{'HEV_Ctrl_Info', 1, 'Bus: HEV_Ctrl_Info_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HEV control information signals' };...
{'EngineCtrl_Info', 1, 'Bus: EngineCtrl_Info_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'ECU output information signals' };...
 } ...
 } ...
{...
'Ctrl_intg_Bus',...
'',...
sprintf('Control signal integration bus'), ...
'Auto',...
'-1', {...
{'EngineCtrl', 1, 'Bus: EngineCtrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Enginer control signal bus' };...
{'TransmCtrl', 1, 'Bus: TransmCtrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Transmisson control signal bus' };...
{'MotorCtrl', 1, 'Bus: MotorCtrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Motor control signal bus' };...
{'BrakeCtrl', 1, 'Bus: BrakeCtrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Brake control signal bus' };...
{'SteerCtrl', 1, 'Bus: SteerCtrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Steering control signal' };...
{'HVAC_Ctrl', 1, 'Bus: HVAC_Ctrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HVAC control signal' };...
{'BodyCtrl', 1, 'Bus: BodyCtrl_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Body control output signal' };...
 } ...
 } ...
 }';
 Simulink.Bus.cellToObject(cellInfo);
 clear cellInfo 
