
cellInfo = { ...
{...
'Transm_sensor_Bus',...
'',...
sprintf('トランスミッションセンサ'), ...
'Auto',...
'-1', {...
{'N_Axle', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rpm', '' };...
{'N_Turbine', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rpm', '' };...
 } ...
 } ...
{...
'Transm_out_Bus',...
'',...
sprintf('トランスミッション出力'), ...
'Auto',...
'-1', {...
{'EngSpd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rad/s', '' };...
{'DrvShaftSpd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rad/s', '' };...
 } ...
 } ...
{...
'Transm_in_Bus',...
'',...
sprintf('トランスミッション入力'), ...
'Auto',...
'-1', {...
{'Trq_in', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', '' };...
{'DrvShaftTrq', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'N*m', '' };...
 } ...
 } ...
 }';
 Simulink.Bus.cellToObject(cellInfo);
 clear cellInfo 
