
cellInfo = { ...
{...
'Vehicle_sensor_Bus',...
'',...
sprintf('車両センサ'), ...
'Auto',...
'-1', {...
{'Motor_sensor', 1, 'Bus: Motor_sensor_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HEVモーターセンサ' };...
{'Battery_sensor', 1, 'Bus: Battery_sensor_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HEVバッテリーセンサ' };...
{'HEV_sensor', 1, 'Bus: HEV_sensor_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HEVセンサ' };...
{'Engine_sensor', 1, 'Bus: Engine_sensor_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'エンジンセンサ' };...
{'Transm_sensor', 1, 'Bus: Transm_sensor_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'トランスミッションセンサ' };...
{'Brake_sensor', 1, 'Bus: Brake_sensor_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'ブレーキセンサ' };...
{'Steer_sensor', 1, 'Bus: Steer_sensor_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'ステアリングセンサ' };...
{'Body_sensor', 1, 'Bus: Body_sensor_Bus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'ボディー系センサ' };...
 } ...
 } ...
{...
'Motor_sensor_Bus',...
'',...
sprintf('HEVモーターセンサ'), ...
'Auto',...
'-1', {...
{'Motor_power', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'W', 'HEVモーター電流' };...
 } ...
 } ...
{...
'Battery_sensor_Bus',...
'',...
sprintf('HEVバッテリーセンサ'), ...
'Auto',...
'-1', {...
{'SOC', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '%', '充電率' };...
 } ...
 } ...
{...
'HEV_sensor_Bus',...
'',...
sprintf('HEVセンサ'), ...
'Auto',...
'-1', {...
{'Ambient_temp', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'degC', '大気温度' };...
 } ...
 } ...
{...
'Engine_sensor_Bus',...
'',...
sprintf('エンジンセンサ'), ...
'Auto',...
'-1', {...
{'EngineSpd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rpm', 'エンジン回転速度' };...
{'CrankAngle', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'deg', 'クランク角度' };...
 } ...
 } ...
{...
'Transm_sensor_Bus',...
'',...
sprintf('トランスミッションセンサ'), ...
'Auto',...
'-1', {...
{'N_Axle', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rpm', 'アウトプットシャフト回転速度' };...
{'N_Turbine', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rpm', 'タービン回転速度' };...
 } ...
 } ...
{...
'Brake_sensor_Bus',...
'',...
sprintf('ブレーキセンサ'), ...
'Auto',...
'-1', {...
{'VehicleSpd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'km/h', '車両速度' };...
 } ...
 } ...
{...
'Steer_sensor_Bus',...
'',...
sprintf('ステアリングセンサ'), ...
'Auto',...
'-1', {...
{'Steer_angle', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'deg', '操舵角' };...
 } ...
 } ...
{...
'Body_sensor_Bus',...
'',...
sprintf('ボディー系センサ'), ...
'Auto',...
'-1', {...
{'Door_open', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'ドアスイッチ' };...
 } ...
 } ...
 }';
 Simulink.Bus.cellToObject(cellInfo);
 clear cellInfo 
