
cellInfo = { ...
{...
'BodyCtrl_Bus',...
'',...
sprintf('Body control signal bus '), ...
'Auto',...
'-1', {...
{'Idlestop_display_BdyCnt', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Idle stop control status display outsignal' };...
 } ...
 } ...
{...
'BodyCtrl_VehCAN_Rx_Bus',...
'',...
sprintf('Body control vehicle CAN receive signal bus '), ...
'Auto',...
'-1', {...
{'BrkCtrl_Vehicle_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'km/h', 'Brake control vehicle speed' };...
{'EngCtrl_Engine_speed', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rpm', 'Engine control engine speed' };...
{'HEVCtrl_IdleStop_status', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'HEV control idle stop status' };...
 } ...
 } ...
{...
'BodyCtrl_VehCAN_Tx_Bus',...
'',...
sprintf('Body control vehicle CAN transmit signal bus '), ...
'Auto',...
'-1', {...
{'BdyCtrl_Idlestop_cancel', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Body control Idle stop cancel ' };...
{'BdyCtrl_Engine_hood_open_flag', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Body control Engine hood open flag' };...
{'BdyCtrl_Door_open_flag', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Body control Door open flag' };...
 } ...
 } ...
 }';
 Simulink.Bus.cellToObject(cellInfo);
 clear cellInfo 
